on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - master

name: Create Release

jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Release Maven package
          uses: samuelmeuli/action-maven-publish@v1
      - name: mvn info
          run: mvn --version
      - name: build
          run: mvn clean package -Dmaven.test.skip=true

